/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Calendar: typeof import('primevue/calendar')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconsIconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}
